# Dapper.CQRS CI build

name: $(Date:yyyy\-MM\-dd)_Dapper_CQRS_Abstractions_CI_$(SourceBranchName)_$(Rev:r)
trigger:
  branches:
   include:
     - main
  paths:
   include:
     - Source/Salix.Dapper.Cqrs.Abstractions
     - Source/Salix.Dapper.Cqrs.Abstractions.Tests

jobs:
- job: Dapper_CQRS_Abstractions_CI
  timeoutInMinutes: 12
  workspace:
    clean: all
  pool:
    vmImage: ubuntu-latest

  variables:
    buildConfiguration: 'Release'
    buildPlatform: 'any cpu'

  steps:
  - checkout: self
    clean: false
    fetchDepth: 1

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '5.0.x'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'Source/Salix.Dapper.Cqrs.Abstractions/Salix.Dapper.Cqrs.Abstractions.csproj'
      configuration: $(buildConfiguration)

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: 'Source/Salix.Dapper.Cqrs.Abstractions.Tests/Salix.Dapper.Cqrs.Abstractions.Tests.csproj'
      arguments: '--blame-hang
                  --blame-hang-timeout 60s
                  /property:GenerateFullPaths=true
                  /consoleloggerparameters:NoSummary
                  /p:CollectCoverage=true
                  /p:CoverletOutputFormat=cobertura
                  /p:ExcludeByAttribute="ExcludeFromCodeCoverage"
                  /p:SkipAutoProps=true
                  /p:CoverletOutput="./TestResults/"'
      testRunTitle: 'Abstraction unit-tests'

  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        *.Tests.dll         
        !**\obj\**
        !**\xunit.runner.visualstudio.testadapter.dll
        !**\xunit.runner.visualstudio.dotnetcore.testadapter.dll
      searchFolder: '$(Build.BinariesDirectory)'
      runSettingsFile: 'testing.runsettings'
      runInParallel: true
      runTestsInIsolation: true
      codeCoverageEnabled: true
      testRunTitle: 'Unit-tests'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      rerunFailedTests: true
      rerunType: 'basedOnTestFailureCount'

