# Dapper.CQRS CI build

name: $(Date:yyyy\-MM\-dd)_Dapper_CQRS_CI_$(SourceBranchName)_$(Rev:r)
trigger:
- main

jobs:
- job: Dapper_CQRS_CI
  timeoutInMinutes: 12
  workspace:
    clean: all
  pool:
    vmImage: windows-latest

  variables:
    buildConfiguration: 'Release'
    buildPlatform: 'any cpu'

  steps:
  - checkout: self
    clean: false
    fetchDepth: 1

  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet 5.9.x'
    inputs:
      versionSpec: '5.9.x'
  
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'
      includeNuGetOrg: true
      verbosityRestore: 'Normal'

  - task: VSBuild@1
    inputs:
      solution: '**\*.sln'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      clean: true
      maximumCpuCount: true
