# Dapper.CQRS CI build

name: $(Date:yyyy\-MM\-dd)_Dapper_CQRS_Abstractions_CI_$(SourceBranchName)_$(Rev:r)
trigger:
  branches:
   include:
     - main
  paths:
   include:
     - Source/Salix.Dapper.Cqrs.Abstractions
     - Source/Salix.Dapper.Cqrs.Abstractions.Tests

jobs:
- job: Dapper_CQRS_Abstractions_CI
  timeoutInMinutes: 12
  workspace:
    clean: all
  pool:
    vmImage: ubuntu-latest

  variables:
    buildConfiguration: 'Release'
    buildPlatform: 'any cpu'

  steps:
  - checkout: self
    clean: false
    fetchDepth: 1

  - task: UseDotNet@2
    displayName: 'Use .Net 5.0.x'
    inputs:
      packageType: 'sdk'
      version: '5.0.x'

  - task: DotNetCoreCLI@2
    displayName: 'Build Abstractions'
    inputs:
      command: 'build'
      projects: 'Source/Salix.Dapper.Cqrs.Abstractions/Salix.Dapper.Cqrs.Abstractions.csproj'
      configuration: $(buildConfiguration)

  - task: DotNetCoreCLI@2
    displayName: 'Run tests'
    inputs:
      command: 'test'
      projects: 'Source/Salix.Dapper.Cqrs.Abstractions.Tests/Salix.Dapper.Cqrs.Abstractions.Tests.csproj'
      arguments: '--blame-hang
                  --blame-hang-timeout 60s
                  /property:GenerateFullPaths=true
                  /consoleloggerparameters:NoSummary
                  /p:CollectCoverage=true
                  /p:CoverletOutputFormat=cobertura
                  /p:ExcludeByAttribute="ExcludeFromCodeCoverage"
                  /p:SkipAutoProps=true
                  /p:CoverletOutput="./TestResults/"'
      testRunTitle: 'Abstraction unit-tests'

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish test results'
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/Source/Salix.Dapper.Cqrs.Abstractions.Tests/TestResults/coverage.cobertura.xml'
      failIfCoverageEmpty: true