# Dapper.CQRS CI build

name: $(Date:yyyy\-MM\-dd)_Dapper_CQRS_Testing_MsSql_xUnit_CI_$(SourceBranchName)_$(Rev:r)
trigger:
  branches:
   include:
     - main
  paths:
   include:
     - Source/Salix.Dapper.Cqrs.Testing.XUnit
     - Source/Salix.Dapper.Cqrs.MsSql
     - Source/Salix.Dapper.Cqrs.MsSql.Tests
     - Source/Salix.Dapper.Cqrs.Abstractions
     - Source/Salix.Dapper.Cqrs.Abstractions.Tests

jobs:
- job: Dapper_CQRS_Testing_MsSql_xUnit_CI
  timeoutInMinutes: 12
  workspace:
    clean: all
  pool:
    vmImage: ubuntu-latest

  variables:
    buildConfiguration: 'Release'
    buildPlatform: 'any cpu'

  steps:
  - checkout: self
    clean: false
    fetchDepth: 1

  - task: UseDotNet@2
    displayName: 'Use .Net 6.0.x'
    inputs:
      packageType: 'sdk'
      version: '6.0.x'
      includePreviewVersions: true

  - task: DotNetCoreCLI@2
    displayName: 'Build MsSql'
    inputs:
      command: 'build'
      projects: 'Source/Salix.Dapper.Cqrs.MsSql.Testing.XUnit/Salix.Dapper.Cqrs.MsSql.Testing.XUnit.csproj'
      configuration: $(buildConfiguration)
